name = "AwesomeEquations"
uuid = "9540e7ae-5ac7-4892-972e-fd18f4264ef9"
authors = ["Syver Døving Agdestein <syverda@icloud.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
